# Validation options

# include column in cleaned file options

# header rows options

# sheets and colums per sheet

# SH_*** = ''
# COL_***_** = ''
# COLS_*** = []

CONFIG_FILE_POSTFIX = '_config'
CONFIG_FILE_EXTENSION = '.xlsx'
VALIDATION_DEFAULT = 'DEFAULT'
VALIDATION_IGNORE_UNNAMED_END = 'IGNORE_UNNAMED_END'
VALIDATION_OPTIONS = ['DEFAULT', 'IGNORE_UNNAMED_END']
CLEANED_INCLUDE = 'YES'  # include column; if exist translated or hashed - include both
CLEANED_EXCLUDE = 'NO'  # column not included
CLEANED_TRANSFORMED_ONLY = 'TRANSFORMED_ONLY'  # for translated and hashed - include only those
CLEANED_OPTIONS = [CLEANED_INCLUDE, CLEANED_EXCLUDE, CLEANED_TRANSFORMED_ONLY]
HEADER_ORIGINAL_ONLY = 'ORIGINAL_ONLY'  # only original column names included (one row)
HEADER_TRANSLATED_ONLY = 'TRANSLATED_ONLY'  # only translated column names included (one row)
HEADER_ORIGINAL_TRANSLATED = 'ORIGINAL_TRANSLATED'  # both original and translated column names included - two rows
HEADER_ROWS_OPTIONS = [HEADER_ORIGINAL_ONLY, HEADER_TRANSLATED_ONLY, HEADER_ORIGINAL_TRANSLATED]
POPULATION_CUSTOM = 'CUSTOM'
POPULATION_BUILTIN = 'BUILTIN'
POPULATION_PROVIDED = 'PROVIDED'
POPULATION_VALUES_MAPPING = 'VALUES_MAPPING'
POPULATION_STRATEGY_OPTIONS = [POPULATION_BUILTIN, POPULATION_CUSTOM, POPULATION_PROVIDED, POPULATION_VALUES_MAPPING]
DTYPE_OBJECT = 'object'

TEMPLATES_SHEET = 'Templates'
TEMPLATES_SHEET_COLUMN_TEMPLATE = 'Template'
TEMPLATES_SHEET_COLUMN_SKIPROWS = 'SkipRows'
TEMPLATES_SHEET_COLUMN_HEADERROW = 'HeaderRow'
TEMPLATES_SHEET_COLUMN_SKIPFOOTERROWS = 'SkipFooterRows'
TEMPLATES_SHEET_COLUMN_VALIDATION = 'Validation'
TEMPLATES_SHEET_COLUMN_DOCTYPE = 'DocumentType'
TEMPLATES_SHEET_COLUMN_CLEANED = 'CleanedHeaderRows'
TEMPLATES_SHEET_COLUMN_ENRICHED = 'EnrichedHeaderRows'
TEMPLATES_SHEET_COLUMN_HEADERLESS = 'Headerless'
TEMPLATES_SHEET_COLUMN_HEADER_MULTIROW = 'HeaderMultirows'
TEMPLATES_SHEET_COLUMN_CROP_LAST_COLUMN = 'ExcelCropLastColumn'
TEMPLATES_SHEET_COLUMN_GROUPING = 'SpecialGrouping'
TEMPLATES_SHEET_COLUMN_EXTRACT = 'ExtractPattern'
TEMPLATES_SHEET_COLUMN_SMART_FOOTER = 'Smart_Footer'


TEMPLATES_SHEET_COLUMNS_OBLIGATORILY = [TEMPLATES_SHEET_COLUMN_TEMPLATE, TEMPLATES_SHEET_COLUMN_SKIPROWS,
                                        TEMPLATES_SHEET_COLUMN_HEADERROW, TEMPLATES_SHEET_COLUMN_SKIPFOOTERROWS,
                                        TEMPLATES_SHEET_COLUMN_VALIDATION, TEMPLATES_SHEET_COLUMN_CLEANED,
                                        TEMPLATES_SHEET_COLUMN_ENRICHED]
TEMPLATES_SHEET_COLUMNS_ALL = [TEMPLATES_SHEET_COLUMN_TEMPLATE, TEMPLATES_SHEET_COLUMN_SKIPROWS,
                               TEMPLATES_SHEET_COLUMN_HEADERROW, TEMPLATES_SHEET_COLUMN_SKIPFOOTERROWS,
                               TEMPLATES_SHEET_COLUMN_VALIDATION, TEMPLATES_SHEET_COLUMN_CLEANED,
                               TEMPLATES_SHEET_COLUMN_ENRICHED, TEMPLATES_SHEET_COLUMN_HEADER_MULTIROW,
                               TEMPLATES_SHEET_COLUMN_CROP_LAST_COLUMN, TEMPLATES_SHEET_COLUMN_GROUPING,
                               TEMPLATES_SHEET_COLUMN_SMART_FOOTER]

COLUMNS_SHEET = 'Columns'
COLUMNS_SHEET_COLUMN_TEMPLATE = 'Template'
COLUMNS_SHEET_COLUMN_COLUMN = 'Column'
COLUMNS_SHEET_COLUMN_TYPE = 'Type'
COLUMNS_SHEET_COLUMN_RENAMED = 'ColumnRenamed'
COLUMNS_SHEET_COLUMN_DICTIONARY = 'Dictionary'
COLUMNS_SHEET_COLUMN_HASH = 'Hash'
COLUMNS_SHEET_COLUMN_CLEAN = 'Clean'
COLUMNS_SHEET_COLUMN_INCLUDE = 'IncludeInClean'
COLUMNS_SHEET_COLUMN_SIZE = 'Size'
COLUMNS_SHEET_COLUMN_CONSTRAINT = 'Constraint'  # todo: rename to "column type" ?
COLUMNS_SHEET_COLUMN_SYNTAX = 'Syntax'
COLUMN_SHEET_COLUMN_EXCLUDE_SOA = 'ExcludeSOA'
COLUMNS_SHEET_COLUMN_MANDATORY_VALUE = 'MandatoryValue'
COLUMNS_SHEET_COLUMN_CONFIG_ORIGIN = 'ConfigOrigin'
COLUMNS_SHEET_COLUMN_TMPLT_ORIGIN = 'TemplateOrigin'
COLUMNS_SHEET_COLUMN_TRANSL_STATUS = 'Transl.Status'
COLUMNS_SHEET_COLUMN_GROUP_BY = 'GroupBy'
COLUMNS_SHEET_COLUMN_SUMMARIZATION = 'SummarizationGroupBy'
COLUMNS_SHEET_COLUMN_MANDATORY_COLUMN = 'MandatoryColumn'

COLUMN_ADD_PREFIX = 'ADD_'

COLUMNS_SHEET_COLUMNS = [
    COLUMNS_SHEET_COLUMN_TEMPLATE, COLUMNS_SHEET_COLUMN_COLUMN, COLUMNS_SHEET_COLUMN_TYPE, COLUMNS_SHEET_COLUMN_RENAMED,
    COLUMNS_SHEET_COLUMN_DICTIONARY, COLUMNS_SHEET_COLUMN_HASH, COLUMNS_SHEET_COLUMN_CLEAN,
    COLUMNS_SHEET_COLUMN_INCLUDE, COLUMNS_SHEET_COLUMN_SIZE, COLUMNS_SHEET_COLUMN_GROUP_BY, COLUMNS_SHEET_COLUMN_CONSTRAINT,
    COLUMNS_SHEET_COLUMN_SYNTAX,  COLUMNS_SHEET_COLUMN_MANDATORY_VALUE, COLUMNS_SHEET_COLUMN_SUMMARIZATION,
    COLUMNS_SHEET_COLUMN_CONFIG_ORIGIN, COLUMNS_SHEET_COLUMN_TMPLT_ORIGIN, COLUMNS_SHEET_COLUMN_TRANSL_STATUS,
    COLUMN_SHEET_COLUMN_EXCLUDE_SOA, COLUMNS_SHEET_COLUMN_MANDATORY_COLUMN
]
COLUMNS_SHEET_COLUMNS_OBLIGATORY = [
    COLUMNS_SHEET_COLUMN_TEMPLATE, COLUMNS_SHEET_COLUMN_COLUMN, COLUMNS_SHEET_COLUMN_TYPE, COLUMNS_SHEET_COLUMN_RENAMED,
    COLUMNS_SHEET_COLUMN_DICTIONARY, COLUMNS_SHEET_COLUMN_HASH, COLUMNS_SHEET_COLUMN_CLEAN,
    COLUMNS_SHEET_COLUMN_INCLUDE]

COLUMNS_SHEET_COLUMNS_VALIDATION = [
    COLUMNS_SHEET_COLUMN_SYNTAX, COLUMNS_SHEET_COLUMN_CONSTRAINT, COLUMNS_SHEET_COLUMN_MANDATORY_VALUE,
    COLUMN_SHEET_COLUMN_EXCLUDE_SOA
]

TRANSLATIONS_SHEET = 'Translations'
TRANSLATIONS_SHEET_COLUMN_DICTIONARY = 'Dictionary'
TRANSLATIONS_SHEET_COLUMN_VALUE = 'Value'
TRANSLATIONS_SHEET_COLUMN_TRANSLATED = 'Translated'
TRANSLATIONS_SHEET_COLUMNS = [
    TRANSLATIONS_SHEET_COLUMN_DICTIONARY, TRANSLATIONS_SHEET_COLUMN_VALUE, TRANSLATIONS_SHEET_COLUMN_TRANSLATED
]

SERVICETEMPLATES_SHEET = 'ServiceTemplates'
SERVICETEMPLATES_SHEET_COLUMN_COLUMN = 'Column'
SERVICETEMPLATES_SHEET_COLUMN_PSTRATEGY = 'PopulationStrategy'
SERVICETEMPLATES_SHEET_COLUMN_VNAME = 'VisibleName'
SERVICETEMPLATES_SHEET_PARAM1 = 'Param1'
SERVICETEMPLATES_SHEET_PARAM2 = 'Param2'
SERVICETEMPLATES_SHEET_COLUMNS = [SERVICETEMPLATES_SHEET_COLUMN_COLUMN, SERVICETEMPLATES_SHEET_COLUMN_PSTRATEGY,
                                  SERVICETEMPLATES_SHEET_COLUMN_VNAME]
GENERAL_SHEET = 'General'
GENERAL_SHEET_COLUMN_CLIENT_NAME = 'Client_Name'
GENERAL_SHEET_COLUMN_CLIENT_ALIAS = 'Client_Alias'
GENERAL_SHEET_COLUMN_FILE_INCLUDE = 'File_Include_Regexp'
GENERAL_SHEET_COLUMN_FOLDER_EXCLUDE = 'Folder_Exclude_Regexp'
GENERAL_SHEET_COLUMN_CLIENT_UTILS = 'Client_Utils'
GENERAL_SHEET_COLUMN_EXCEL_HEADER_LINES = 'Excel_Header_Lines'
GENERAL_SHEET_COLUMN_CHUNK_SIZE = 'Chunk_Size'
GENERAL_SHEET_COLUMN_EXCEL_PREPROC_SHEETS = 'Excel_Preproc_Sheets'
GENERAL_SHEET_COLUMN_SMART_FOOTER = 'Smart_Footer'
GENERAL_SHEET_COLUMN_SMART_HEADER = 'Smart_Header'
GENERAL_SHEET_COLUMN_COLUMN_ORDER = 'Column_Order'
GENERAL_SHEET_COLUMN_NEW_COLUMNS = 'New_Columns'
GENERAL_SHEET_COLUMN_CHECK_ON_PII = 'Check_On_PII'

GENERAL_SHEET_COLUMNS = [
    GENERAL_SHEET_COLUMN_CLIENT_NAME, GENERAL_SHEET_COLUMN_CLIENT_ALIAS,
    GENERAL_SHEET_COLUMN_FILE_INCLUDE, GENERAL_SHEET_COLUMN_FOLDER_EXCLUDE
]

SHEET_SHEET_RENAME = 'SheetRename'
COLUMN_SHEET_RENAME_SOURCE_NAME = 'SourceName'
COLUMN_SHEET_RENAME_TARGET_NAME = 'TargetName'
SHEET_RENAME_COLUMNS = [COLUMN_SHEET_RENAME_SOURCE_NAME, COLUMN_SHEET_RENAME_TARGET_NAME]
SHEET_TEMPLATE_MAPPING = 'TemplateMapping'
COLUMN_TEMPLATE_MAPPING_PATTERN = 'FilenamePattern'
COLUMN_TEMPLATE_MAPPING_OUT_TEMPLATE = 'OutTemplate'
COLUMN_TEMPLATE_MAPPING_GROUP = 'Group'
COLUMN_TEMPLATE_MAPPING_KEY = 'Key'
COLUMNS_TEMPLATE_MAPPING = [
    COLUMN_TEMPLATE_MAPPING_PATTERN, COLUMN_TEMPLATE_MAPPING_OUT_TEMPLATE,
    COLUMN_TEMPLATE_MAPPING_GROUP, COLUMN_TEMPLATE_MAPPING_KEY
]

SHEET_INCOMING_CSV = 'IncomingCSV'
COLUMN_INCOMING_CSV_FILE_REGEXP = 'File_Regexp'
COLUMN_INCOMING_CSV_ENCODING = 'Encoding'
COLUMN_INCOMING_CSV_DELIMITER = 'Delimiter'
COLUMN_INCOMING_CSV_EXTENSION = 'FileExtension'
COLUMN_INCOMING_CSV_FIXED_WIDTH = 'Fixed_Width'
COLUMN_INCOMING_CSV_FIXED_WIDTH_TEMPLATE = 'Fixed_Width_Template'
COLUMNS_INCOMING_CSV = [COLUMN_INCOMING_CSV_FILE_REGEXP, COLUMN_INCOMING_CSV_ENCODING, COLUMN_INCOMING_CSV_DELIMITER]

SHEET_SHEET_PROCESS = 'SheetToProcess'
COLUMN_SHEET_PROCESS_FILE_REGEXP = 'File_Regexp'
COLUMN_SHEET_PROCESS_SHEET_REGEXP = 'Sheet_Regexp'
COLUMNS_SHEET_PROCESS = [COLUMN_SHEET_PROCESS_FILE_REGEXP, COLUMN_SHEET_PROCESS_SHEET_REGEXP]

SHEET_SYNTAX_VALIDATION_DICTIONARIES = 'SyntValidationDicts'

SHEET_FORCE_CROP = 'ForceCopy'
COLUMN_FORCE_CROP_FILE_REGEXP = 'FileRegexp'
COLUMNS_FORCE_CROP = [COLUMN_FORCE_CROP_FILE_REGEXP]
KNOWN_SHEETS = [TEMPLATES_SHEET, COLUMNS_SHEET, TRANSLATIONS_SHEET, SERVICETEMPLATES_SHEET, GENERAL_SHEET,
                SHEET_SHEET_RENAME, SHEET_TEMPLATE_MAPPING, SHEET_INCOMING_CSV,
                SHEET_SHEET_PROCESS, SHEET_FORCE_CROP]

INCOMING_CSV_ENCODING = 'Incoming_CSV_Encoding'
INCOMING_CSV_DELIMITER = 'Incoming_CSV_Delimiter'
GROUPING = '_group'
